version: '3.8'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - proxy_network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - wordpress_logs:/var/log/apache2
    networks:
      - proxy_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx_data/certs:/etc/nginx/certs
      - ./nginx_data/conf.d:/etc/nginx/conf.d
      - ./nginx_data/html:/usr/share/nginx/html
      - ./nginx_data/modsecurity:/etc/nginx/modsecurity
      - nginx_logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - proxy_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    depends_on:
      - db
    networks:
      - proxy_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx_data/certs:/etc/letsencrypt
      - ./nginx_data/html:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
    command: certonly --webroot --webroot-path=/usr/share/nginx/html -d example.com
    restart: unless-stopped

  webalizer:
    image: toughiq/webalizer:latest
    volumes:
      - nginx_logs:/logs
      - ./nginx_data/html:/var/www/webalizer
    restart: unless-stopped
    networks:
      - proxy_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./wordpress/db_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ./wordpress/wordpress_data
      o: bind
  nginx_data:
    driver: local
    driver_opts:
      type: none
      device: ./nginx_data/
      o: bind
  db_logs:
    driver: local
    driver_opts:
      type: none
      device: ./log_data/db_logs
      o: bind
  wordpress_logs:
    driver: local
    driver_opts:
      type: none
      device: ./log_data/wordpress_logs
      o: bind
  nginx_logs:
    driver: local
    driver_opts:
      type: none
      device: ./log_data/nginx_logs
      o: bind

networks:
  proxy_network:
    driver: bridge
