SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On

# デフォルトのModSecurityのルールを追加
Include /etc/nginx/modsec-rules/crs-setup.conf
Include /etc/nginx/modsec-rules/rules/*.conf

# ログファイルの設定
SecAuditLog /var/log/nginx/modsecurity/audit.log
SecDebugLog /var/log/nginx/modsecurity/debug.log
SecDebugLogLevel 3
