#!/usr/bin/env bash
# =====================================================================
# Cloudflare IP 一覧を取得し set_real_ip_from ファイルを再生成
# 月次 cron ・余裕をもって実行推奨 (Cloudflare は長期間安定だが、拡張可能性あり)
#   0 5 1 * * /path/to/platform/scripts/update-cloudflare-ips.sh
# =====================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${PLATFORM_DIR}/nginx_conf/conf.d/cloudflare-realip.conf"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

V4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
V6="$(curl -fsS https://www.cloudflare.com/ips-v6)"

if [[ -z "$V4" || -z "$V6" ]]; then
  echo "ERROR: failed to fetch Cloudflare IP lists" >&2
  exit 1
fi

{
  cat <<'EOF'
# =====================================================================
# Auto-generated by scripts/update-cloudflare-ips.sh
# Source: https://www.cloudflare.com/ips-v4 / ips-v6
# 配置方法:
#   sudo cp cloudflare-realip.conf ../nginx_data/conf.d/cloudflare-realip.conf
#   sudo docker compose exec nginx nginx -s reload
# =====================================================================
EOF
  echo "# Generated at: $(date -Iseconds)"
  echo ""
  echo "# IPv4"
  while IFS= read -r net; do [[ -n "$net" ]] && echo "set_real_ip_from $net;"; done <<< "$V4"
  echo ""
  echo "# IPv6"
  while IFS= read -r net; do [[ -n "$net" ]] && echo "set_real_ip_from $net;"; done <<< "$V6"
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP"

if cmp -s "$TMP" "$OUT"; then
  echo "[$(date -Iseconds)] No change."
else
  mv "$TMP" "$OUT"
  trap - EXIT
  echo "[$(date -Iseconds)] Updated ${OUT}"
  if docker compose -f "${PLATFORM_DIR}/docker-compose.yml" ps --status running --quiet nginx | grep -q .; then
    docker compose -f "${PLATFORM_DIR}/docker-compose.yml" exec nginx nginx -t \
      && docker compose -f "${PLATFORM_DIR}/docker-compose.yml" exec nginx nginx -s reload \
      && echo "  nginx reloaded"
  fi
fi
